 export const menu = [
{
    id: 1,
    tags: ["TRADICIONAL"],
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    photo: '/src/assets/images/expressoTradicional.png',
    price: 9.9,
  },
  {
    id: 2,
    tags: ["TRADICIONAL"],
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    photo: '/src/assets/images/expressoAmericano.png',
    price: 9.9,
  },
  {
    id: 3,
    tags: ["TRADICIONAL"],
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    photo: '/src/assets/images/expressoCremoso.png',
    price: 9.9,
  },
  {
    id: 4,
    tags: ["TRADICIONAL", "GELADO"],
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    photo: '/src/assets/images/expressoGelado.png', 
    price: 9.9,
  },
  {
    id: 5,
    tags: ["TRADICIONAL", "COM LEITE"],
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    photo: '/src/assets/images/cafe-com-leite.png',
    price: 9.9,
  },
  {
    id: 6,
    tags: ["TRADICIONAL", "COM LEITE"],
    name: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
      photo: '/src/assets/images/latte.png' ,
    price: 9.9,
  },
  {
    id: 7,
    tags: ["TRADICIONAL", "COM LEITE"],
    name: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
      photo: '/src/assets/images/capuccino.png' ,
    price: 9.9,
  },
  {
    id: 8,
    tags: ["TRADICIONAL", "COM LEITE"],
    name: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
      photo: '/src/assets/images/macchiato.png' ,
    price: 9.9,
  },
  {
    id: 9,
    tags: ["TRADICIONAL", "COM LEITE"],
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    photo: '/src/assets/images/mocaccino.png',
    price: 9.9,
  },
  {
    id: 10,
    tags: ["ESPECIAL", "COM LEITE"],
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    photo: '/src/assets/images/chocolate-quente.png',
    price: 9.9,
  },
  {
    id: 11,
    tags: ["ESPECIAL", "ALCOÓLICO", "GELADO"],
    name: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
      photo: '/src/assets/images/cubano.png',
    price: 9.9,
  },
  {
    id: 12,
    tags: ["ESPECIAL"],
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    photo: '/src/assets/images/havaiano.png', 
    price: 9.9,
  },
  {
    id: 13,
    tags: ["ESPECIAL"],
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    photo: '/src/assets/images/arabe.png',
    price: 9.9,
  },
  {
    id: 14,
    tags: ["ESPECIAL", "ALCOÓLICO"],
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    photo: '/src/assets/images/irlandes.png' ,
    price: 9.9,
  },
];